import { getLocale } from "../../paraglide/runtime";

type LocalizedText = {
  zh: string;
  en: string;
};

export interface BackupSourceOption {
  id: string;
  path: string;
  title: LocalizedText;
  description: LocalizedText;
}

export interface ExcludePreset {
  id: string;
  patterns: string[];
  title: LocalizedText;
  description: LocalizedText;
}

export const DEFAULT_PLAN_EXCLUDES = ["**/.DS_Store"];

export const BACKUP_SOURCE_OPTIONS: BackupSourceOption[] = [
  {
    id: "docker",
    path: "/source/docker",
    title: { zh: "Docker 服务", en: "Docker services" },
    description: {
      zh: "Compose、环境变量、持久化目录和自建服务代码。",
      en: "Compose files, environment files, persistent data, and local service code.",
    },
  },
  {
    id: "home-assistant",
    path: "/source/home-assistant",
    title: { zh: "Home Assistant", en: "Home Assistant" },
    description: {
      zh: "配置、自动化、自定义组件和集成设置。",
      en: "Configuration, automations, custom components, and integrations.",
    },
  },
  {
    id: "docker-named-volumes",
    path: "/source/docker-volumes/telegram-data",
    title: { zh: "Docker 命名卷", en: "Docker named volumes" },
    description: {
      zh: "Telegram 服务状态；恢复时可迁移为普通持久化目录。",
      en: "Telegram service state, portable to a regular persistent directory during recovery.",
    },
  },
  {
    id: "web-live",
    path: "/source/web-live",
    title: { zh: "直播代理", en: "Live proxy" },
    description: {
      zh: "直播代理代码、Compose 和频道配置。",
      en: "Live proxy code, Compose configuration, and channel data.",
    },
  },
  {
    id: "web-autoaccount",
    path: "/source/web-autoaccount",
    title: { zh: "自动化服务数据", en: "Automation service data" },
    description: {
      zh: "自动化服务配置与附件；数据库使用备份前生成的一致副本。",
      en: "Automation settings and artifacts; the database uses a consistent pre-backup copy.",
    },
  },
  {
    id: "dsm-certificates",
    path: "/source/dsm-certificates",
    title: { zh: "DSM 证书", en: "DSM certificates" },
    description: {
      zh: "证书、私钥和 DSM 服务证书配置。",
      en: "Certificates, private keys, and DSM service certificate configuration.",
    },
  },
  {
    id: "dsm-package-config",
    path: "/source/dsm-packages",
    title: { zh: "DSM 套件配置", en: "DSM package settings" },
    description: {
      zh: "Container Manager、Download Station、DDNS 和 VMM 等套件设置。",
      en: "Settings for Container Manager, Download Station, DDNS, VMM, and other packages.",
    },
  },
  {
    id: "recovery-staging",
    path: "/staging",
    title: { zh: "群晖恢复资料", en: "Synology recovery files" },
    description: {
      zh: "DSM 重建资料、完整 Docker 清单和应用数据库一致副本。",
      en: "DSM reconstruction facts, a complete Docker inventory, and consistent application database copies.",
    },
  },
  {
    id: "time-machine",
    path: "/source/time-machine",
    title: { zh: "Time Machine", en: "Time Machine" },
    description: {
      zh: "Mac 的完整本地备份包；此备份任务只用于异地容灾。",
      en: "The complete local Mac backup bundle, copied only for off-site recovery.",
    },
  },
];

export const EXCLUDE_PRESETS: ExcludePreset[] = [
  {
    id: "macos-metadata",
    patterns: DEFAULT_PLAN_EXCLUDES,
    title: { zh: "macOS 元数据", en: "macOS metadata" },
    description: {
      zh: "跳过 Finder 自动生成的 .DS_Store 文件。",
      en: "Omits .DS_Store files generated by Finder.",
    },
  },
  {
    id: "synology-metadata",
    patterns: ["**/@eaDir/**"],
    title: { zh: "群晖缩略图元数据", en: "Synology thumbnail metadata" },
    description: {
      zh: "@eaDir 目录由群晖自动生成，不上传。",
      en: "Omits @eaDir directories generated by Synology.",
    },
  },
  {
    id: "generated-files",
    patterns: [
      "**/.cache/**",
      "**/.next/**",
      "**/.pytest_cache/**",
      "**/.ruff_cache/**",
      "**/__pycache__/**",
      "**/cache/**",
      "**/logs/**",
      "**/node_modules/**",
      "**/temp/**",
      "**/tmp/**",
      "**/*.log",
      "**/*.log.*",
    ],
    title: {
      zh: "日志、缓存和临时文件",
      en: "Logs, caches, and temporary files",
    },
    description: {
      zh: "运行时会重新生成，不占用 115 上传流量。",
      en: "Regenerated at runtime and omitted from 115 uploads.",
    },
  },
  {
    id: "git-history",
    patterns: ["**/.git/**"],
    title: { zh: "Git 提交历史", en: "Git history" },
    description: {
      zh: "不备份 .git；项目当前文件仍保留，避免遗漏 Docker 配置和服务数据。",
      en: "Omits .git while retaining working files that may contain Docker configuration or service data.",
    },
  },
  {
    id: "old-transfer-cache",
    patterns: ["/source/docker/SYNC/**", "/source/docker/SYNC_BIU/**"],
    title: { zh: "旧传输缓存", en: "Legacy transfer caches" },
    description: {
      zh: "SYNC 和 SYNC_BIU 目录不上传。",
      en: "Omits the SYNC and SYNC_BIU directories.",
    },
  },
  {
    id: "backrest-runtime",
    patterns: ["/source/docker/autofilm-suite/autofilm-core/data/backrest/**"],
    title: { zh: "Backrest 运行目录", en: "Backrest runtime data" },
    description: {
      zh: "排除缓存、任务记录和本地存储库元数据，避免备份包含自身。",
      en: "Omits cache, operation history, and local metadata so the backup does not include itself.",
    },
  },
  {
    id: "live-databases",
    patterns: [
      "/source/docker/alist/data.db*",
      "/source/docker/autofilm-suite/autofilm-core/data/autofilm.sqlite*",
      "/source/docker/jellyfin/config/data/*.db*",
      "/source/docker/subhub/data/subhub.db*",
      "/source/docker/localproxy-data/localproxy.db*",
      "/source/docker/nas-gateway-manager/data/manager.db*",
      "/source/web-autoaccount/automation.db*",
      "/source/home-assistant/home-assistant_v2.db*",
    ],
    title: { zh: "运行中的数据库原文件", en: "Live database files" },
    description: {
      zh: "应用数据库改用备份前生成的一致副本；Home Assistant 历史数据库不上传。",
      en: "Application databases use consistent pre-backup copies; Home Assistant history is omitted.",
    },
  },
  {
    id: "staging-control",
    patterns: ["/staging/control/**"],
    title: { zh: "备份协调文件", en: "Backup coordination files" },
    description: {
      zh: "主机与备份服务之间的一次性请求和执行日志。",
      en: "One-time requests and execution logs exchanged by the host and backup service.",
    },
  },
  {
    id: "dsm-package-runtime",
    patterns: ["/source/dsm-packages/appconf/Virtualization/ccc/etcd.data/**"],
    title: { zh: "DSM 套件运行数据", en: "DSM package runtime data" },
    description: {
      zh: "跳过 VMM 活动状态；可迁移的套件配置仍会上传。",
      en: "Omits active VMM state while retaining portable package settings.",
    },
  },
];

export const scopeText = (locale = getLocale()) => {
  const zh = locale.toLowerCase().startsWith("zh");
  return {
    backupTitle: zh ? "将备份" : "Backed up",
    backupDescription: zh
      ? "打开需要保存到 115 的内容。"
      : "Enable the content that should be stored offsite.",
    excludeTitle: zh ? "将跳过" : "Skipped",
    excludeDescription: zh
      ? "打开无需上传的内容，例如日志、缓存和临时文件。"
      : "Enable content that does not need to be uploaded, such as logs and caches.",
    enabled: zh ? "已备份" : "Included",
    disabled: zh ? "未备份" : "Not included",
    excluded: zh ? "已排除" : "Excluded",
    included: zh ? "会上传" : "Uploaded",
    partial: zh ? "部分规则生效" : "Partially enabled",
    customPaths: zh ? "其他备份目录" : "Other backup paths",
    customRules: zh ? "其他排除规则" : "Other exclusion rules",
    advancedTitle: zh ? "高级路径与规则" : "Advanced paths and rules",
    advancedDescription: zh
      ? "添加非标准目录或精确规则时使用。"
      : "Use this for custom paths or exact Restic patterns.",
    overviewTitle: zh ? "备份内容" : "Backup content",
    overviewDescription: zh
      ? "每个备份任务会上传哪些内容、跳过哪些内容。"
      : "What each plan uploads and skips.",
    editorDescription: zh
      ? "选择需要上传的内容和可以跳过的内容。"
      : "Choose what to upload and what can be skipped.",
    editPlan: zh ? "编辑内容" : "Edit content",
    planCount: (count: number) =>
      zh ? `${count} 个备份任务` : `${count} backup plans`,
    detailsNav: zh ? "基本信息" : "Details",
    scopeNav: zh ? "备份内容" : "Content",
    scheduleNav: zh ? "自动备份" : "Schedule",
    retentionNav: zh ? "历史版本" : "Retention",
    advancedNav: zh ? "高级设置" : "Advanced",
    noExcludes: zh ? "没有设置排除项" : "No exclusions configured",
    noSources: zh ? "没有设置备份目录" : "No backup paths configured",
    rules: (enabled: number, total: number) =>
      zh ? `${enabled}/${total} 条规则` : `${enabled}/${total} rules`,
  };
};

export const localizeScopeText = (
  value: LocalizedText,
  locale = getLocale(),
) => (locale.toLowerCase().startsWith("zh") ? value.zh : value.en);

export const getKnownSources = (paths: string[]) => {
  const pathSet = new Set(paths);
  return BACKUP_SOURCE_OPTIONS.filter((source) => pathSet.has(source.path));
};

export const getCustomPaths = (paths: string[]) => {
  const knownPaths = new Set(
    BACKUP_SOURCE_OPTIONS.map((source) => source.path),
  );
  return paths.filter((path) => !knownPaths.has(path));
};

export const getPresetMatchCount = (preset: ExcludePreset, rules: string[]) => {
  const ruleSet = new Set(rules);
  return preset.patterns.filter((pattern) => ruleSet.has(pattern)).length;
};

export const getCustomExcludeRules = (rules: string[]) => {
  const knownRules = new Set(
    EXCLUDE_PRESETS.flatMap((preset) => preset.patterns),
  );
  return rules.filter((rule) => !knownRules.has(rule));
};
