name: Release Preview

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  call-reusable-release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      snapshot: true
